services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      .env
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
